# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ShrimpWorks
email: shrimp@shrimpworks.za.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shrimpworks.za.net" # the base hostname & protocol for your site
permalink: "/:year/:month/:day/:title/"
excerpt_separator: ""

github_username:  shrimpza

# Build settings
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate, mini_magick]

# blog entry pagination
paginate: 10
paginate_path: "/page/:num"

# Page collections
collections:
  gallery:
    output: true
    permalink: /gallery/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Gallery configuration
gallerytag:
  magick_lib: mini
  source_dir: assets/gallery
  destination_dir: assets/gallery/thumbs
  thumb_width: 200
  thumb_height: 200
  columns: 0
