# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ShrimpWorks
email: shrimp@shrimpworks.za.net
description: > # this means to ignore newlines until "baseurl:"
  The musings, learnings, photos, code and hobbies of Kenneth Watson.
  Featuring Java, PHP, JavaScript, Linux and other random tutorials, guides
  and projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shrimpworks.za.net" # the base hostname & protocol for your site
permalink: "/:year/:month/:day/:title/"
excerpt_separator: ""

# Build settings
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate, mini_magick]

# blog entry pagination
paginate: 10
paginate_path: "/page/:num"

# category config
category_title_prefix: "Category: "
category_dir: "categories"

# Page collections
collections:
  gallery:
    output: true
    permalink: /gallery/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Gallery configuration
gallerytag:
  magick_lib: mini
  source_dir: assets/gallery
  destination_dir: assets/gallery/thumbs
  thumb_width: 200
  thumb_height: 200
  columns: 0

smileytheme: emoji-one
smileypath: assets/smileys
