# Default image format
format                  :      png

# Default shortcuts for smileys
rock                    :      "\\m/"
wink                    :      ";)"
wink                    :      ";-)"
grin                    :      ":D"
grin                    :      ":-D"
cool                    :      "8)"
cool                    :      "8-)"
smile                   :      ":)"
smile                   :      ":-)"
frown                   :      ":("
frown                   :      ":-("
angry                   :      ">:("
crying                  :      ":`("
crying                  :      ":'("
confused                :      ":S"
confused                :      ":-S)"
surprised               :      ":O"
surprised               :      ":-O)"
tongue-out              :      ":P"
tongue-out              :      ":-P"
speechless              :      ":\\|"
speechless              :      ":-\\|"
lips-sealed             :      ":X"
lips-sealed             :      ":-X"

# Smileys without shortcuts
blush                   :      ""
dozing                  :      ""
embarrassed             :      ""
in-love                 :      ""
peace                   :      ""
thumbs-up               :      ""
thumbs-down             :      ""
sleepy                  :      ""
sick                    :      ""
clap                    :      ""
vomit                   :      ""
pray                    :      ""
whistle                 :      ""
kiss                    :      ""
heart                   :      ""
shout                   :      ""
angel                   :      ""
alien                   :      ""
devil                   :      ""
lips-sealed             :      ""
broken-heart            :      ""
