# Default image format
format                  :      png

# Default shortcuts for smileys
wink                    :      ";-?\\)"
grin                    :      ":-?D"
cool                    :      "8-?\\)"
smile                   :      ":-?\\)"
frown                   :      ":-?\\("
angry                   :      ">:\\("
crying                  :      ":`\\("
confused                :      ":-?S"
surprised               :      ":-?O"
tongue-out              :      ":-?P"
speechless              :      ":-?\\|"
lips-sealed             :      ":-?X"

# Smileys without shortcuts
rock                    :      ""
blush                   :      ""
dozing                  :      ""
embarrassed             :      ""
in-love                 :      ""
peace                   :      ""
thumbs-up               :      ""
thumbs-down             :      ""
sleepy                  :      ""
sick                    :      ""
clap                    :      ""
vomit                   :      ""
pray                    :      ""
whistle                 :      ""
kiss                    :      ""
heart                   :      ""
shout                   :      ""
angel                   :      ""
alien                   :      ""
devil                   :      ""
lips-sealed             :      ""
broken-heart            :      ""
